Repository Chatting-Bar/Chatting-Bar-Server, pull requests merged in 2023-06, with the labels that each got.

#15 [FEAT]: 구독 기능 API 생성
  src/main/java/com/chatbar/domain/user/application/FollowService.java
  src/main/java/com/chatbar/domain/user/domain/Follow.java
  src/main/java/com/chatbar/domain/user/domain/repository/FollowRepository.java
  src/main/java/com/chatbar/domain/user/dto/FollowRes.java
  src/main/java/com/chatbar/domain/user/presentation/UserController.java
Labels: feature 🎄

#17 [FIX]: 카테고리 문제 수정
  src/main/java/com/chatbar/domain/chatroom/application/ChatRoomService.java
  src/main/java/com/chatbar/domain/chatroom/domain/ChatRoom.java
  src/main/java/com/chatbar/domain/chatroom/dto/RoomListRes.java
  src/main/java/com/chatbar/domain/common/CategorySetConverter.java
  src/main/java/com/chatbar/domain/user/application/UserService.java
  src/main/java/com/chatbar/domain/user/domain/User.java
  src/main/java/com/chatbar/domain/user/dto/UserRes.java
Labels: fix ☔️

#18 [FEAT]: 채팅방에 있는 유저 조회 API 추가, 채팅방 조회 API에 속성 추가
  src/main/java/com/chatbar/domain/chatroom/application/ChatRoomService.java
  src/main/java/com/chatbar/domain/chatroom/domain/ChatRoom.java
  src/main/java/com/chatbar/domain/chatroom/domain/UserChatRoom.java
  src/main/java/com/chatbar/domain/chatroom/domain/repository/UserChatRoomRepository.java
  src/main/java/com/chatbar/domain/chatroom/dto/RoomListRes.java
  src/main/java/com/chatbar/domain/chatroom/dto/UserListRes.java
  src/main/java/com/chatbar/domain/chatroom/presentation/ChatRoomController.java
Labels: feature 🎄

#19 [FEAT]: 방 닫기, ID로 구독자 조회 API 생성
  src/main/java/com/chatbar/ChatbarApplication.java
  src/main/java/com/chatbar/domain/chatroom/application/ChatRoomService.java
  src/main/java/com/chatbar/domain/chatroom/domain/ChatRoom.java
  src/main/java/com/chatbar/domain/chatroom/domain/UserChatRoom.java
  src/main/java/com/chatbar/domain/chatroom/domain/repository/UserChatRoomRepository.java
  src/main/java/com/chatbar/domain/chatroom/dto/CloseRoomReq.java
  src/main/java/com/chatbar/domain/chatroom/dto/RoomListRes.java
  src/main/java/com/chatbar/domain/chatroom/presentation/ChatRoomController.java
  src/main/java/com/chatbar/domain/user/application/FollowService.java
  src/main/java/com/chatbar/domain/user/presentation/UserController.java
Labels: feature 🎄

#20 [FEAT]: 방 마감, 얼리기 자동 체크
  src/main/java/com/chatbar/ChatbarApplication.java
  src/main/java/com/chatbar/domain/chatroom/application/ChatRoomService.java
  src/main/java/com/chatbar/domain/chatroom/domain/UserChatRoom.java
  src/main/java/com/chatbar/domain/chatroom/domain/repository/ChatRoomRepository.java
  src/main/java/com/chatbar/domain/chatroom/domain/repository/UserChatRoomRepository.java
Labels: feature 🎄, fix ☔️

#22 [FEAT]: 채팅방 참여기록 조회 API 생성
  src/main/java/com/chatbar/domain/chatroom/application/ChatRoomService.java
  src/main/java/com/chatbar/domain/chatroom/domain/repository/UserChatRoomRepository.java
  src/main/java/com/chatbar/domain/chatroom/dto/RoomListRes.java
  src/main/java/com/chatbar/domain/chatroom/presentation/ChatRoomController.java
Labels: feature 🎄

#25 [FIX]: 방 생성 API response 변경
  src/main/java/com/chatbar/domain/chatroom/application/ChatRoomService.java
  src/main/java/com/chatbar/domain/chatroom/dto/CreateRoomRes.java
Labels: chore 💪

#27 [FEAT]: 방 조회(구독 기준) API 생성
  src/main/java/com/chatbar/domain/chatroom/application/ChatRoomService.java
  src/main/java/com/chatbar/domain/chatroom/domain/repository/ChatRoomRepository.java
  src/main/java/com/chatbar/domain/chatroom/presentation/ChatRoomController.java
Labels: feature 🎄
