Repository Chatting-Bar/Chatting-Bar-Server, pull requests merged in 2023-05, with the labels that each got.

#3 [FEAT]: ChatRoom API 개발
  src/main/java/com/chatbar/domain/chatroom/application/ChatRoomService.java
  src/main/java/com/chatbar/domain/chatroom/domain/ChatRoom.java
  src/main/java/com/chatbar/domain/chatroom/domain/repository/ChatRoomRepository.java
  src/main/java/com/chatbar/domain/chatroom/domain/repository/UserChatRoomRepository.java
  src/main/java/com/chatbar/domain/chatroom/dto/EnterRoomReq.java
  src/main/java/com/chatbar/domain/chatroom/dto/ResultRoomListRes.java
  src/main/java/com/chatbar/domain/chatroom/dto/RoomListRes.java
  src/main/java/com/chatbar/domain/chatroom/presentation/ChatRoomController.java
Labels: feature 🎄

#4 [FEAT]: ChatRoom API 개발
  src/main/java/com/chatbar/domain/chatroom/application/ChatRoomService.java
  src/main/java/com/chatbar/domain/chatroom/domain/ChatRoom.java
  src/main/java/com/chatbar/domain/chatroom/dto/CreateRoomReq.java
  src/main/java/com/chatbar/domain/chatroom/dto/RoomListRes.java
  src/main/java/com/chatbar/domain/chatroom/presentation/ChatRoomController.java
  src/main/java/com/chatbar/domain/common/Category.java
Labels: feature 🎄, fix ☔️

#5 [FEAT]: 유저 강퇴, 얼리기 API 개발
  src/main/java/com/chatbar/domain/chatroom/application/ChatRoomService.java
  src/main/java/com/chatbar/domain/chatroom/domain/UserChatRoom.java
  src/main/java/com/chatbar/domain/chatroom/presentation/ChatRoomController.java
  src/main/java/com/chatbar/domain/common/Category.java
Labels: feature 🎄

#6 [FEAT]: 방조회(최신순,추선순) API 개발
  src/main/java/com/chatbar/domain/chatroom/application/ChatRoomService.java
  src/main/java/com/chatbar/domain/chatroom/presentation/ChatRoomController.java
Labels: feature 🎄

#7 [FIX]: token 길이 변경
  build.gradle
  src/main/java/com/chatbar/domain/auth/domain/Token.java
  src/main/java/com/chatbar/domain/message/dto/MessageDto.java
Labels: fix ☔️, deployment 🐿

#10 [FIX]: 채팅방 시간 예외 생성
  src/main/java/com/chatbar/domain/chatroom/application/ChatRoomService.java
Labels: fix ☔️

#13 [FEAT]: 유저조회 API 개발
  src/main/java/com/chatbar/domain/user/application/UserService.java
  src/main/java/com/chatbar/domain/user/dto/UserRes.java
  src/main/java/com/chatbar/domain/user/presentation/UserController.java
Labels: feature 🎄

#14 [FIX]: 카테고리 값 타입 컬렉션으로 저장
  src/main/java/com/chatbar/domain/chatroom/domain/ChatRoom.java
  src/main/java/com/chatbar/domain/chatroom/domain/UserChatRoom.java
  src/main/java/com/chatbar/domain/user/domain/User.java
Labels: fix ☔️
